[package]
name = "pomelo_kernel"
version = "0.1.0"
authors = ["Dwayne Slater <ds84182@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
clocksource = "0.4"
parking_lot = "0.7.1"
xorshift = "0.1"
